namespace YtDlpGui.Views
{
    [default_interface]
    unsealed runtimeclass DownloadPage : Windows.UI.Xaml.Controls.Page
    {
        DownloadPage();
        YtDlpGui.ViewModels.DownloadViewModel ViewModel{ get; };
        void UrlTextBox_KeyDown(Windows.Foundation.Object sender, Microsoft.UI.Xaml.Input.KeyRoutedEventArgs args);
        void ShowAdvancedFlags_Click(Windows.Foundation.Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }
}
