namespace YtDlpGui.Views
{
    [default_interface]
    unsealed runtimeclass SettingsPage : Windows.UI.Xaml.Controls.Page
    {
        SettingsPage();
        YtDlpGui.ViewModels.SettingsViewModel ViewModel{ get; };
    }
}
